class CfgPatches {
    class SFT_koslovics {
        units[] = {
            "O_IN_Rifleman_01",
            "O_IN_Rifleman_light_01",
            "O_IN_Officer_01",
            "O_IN_Grenadier_01",
            "O_IN_Autorifleman_01",
            "O_IN_Squad_Leader_01",
            "O_IN_Team_Leader_01",
            "O_IN_Marksman_01",
            "O_IN_Rifleman_Disposable_01",
            "O_IN_Medic_01",
            "O_IN_Repair_Specialist_01",
            "O_IN_Explosive_Specialist_01",
            "O_IN_Helicopter_Pilot_01",
            "O_IN_Ammo_Bearer_01",
            "O_IN_Missile_Specialist_AT_01",
            "O_IN_Missile_Specialist_AA_01",
            "O_IN_Engineer_01",
            "O_IN_Crewman_01",
            "O_IN_Pilot_01",
            "O_IN_Helicopter_Crew_01",
            "O_IN_UAV_Operator_01",
            "O_IN_Assist_AutoRifleman_01",
            "O_IN_Assist_Missile_Specialsit_AT_01",
            "O_IN_Assist_Missile_Specialist_AA_01",
            "O_IN_Assist_Heavy_AutoRifleman_01",
            "O_IN_Sharpshooter_01",
            "O_IN_Heavy_AutoRifleman_01",
            "O_IN_Fighter_Pilot_01",
            "O_IN_Mine_Specialist_01",
            "O_IN_Rifleman_Heavy_AT_01",
            "O_IN_Assist_Rifleman_Heavy_AT_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "lambs_danger",
            "aceax_ingame",
            "A3_Sounds_F",
            "WBK_WRS_Mechs",
            "A3_Sounds_F_Exp",
            "lambs_range",
            "RS_Equip_Retention",
            "TKE_Ext_Core",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "acre_sys_components",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "A3_Map_Abramia",
            "GOT_Map_IslaPera",
            "ibr_panthera_c",
            "GO_Map_Farabad_Data",
            "ace_thermals",
            "lambs_formations",
            "zen_attributes",
            "ace_refuel",
            "CUP_Core",
            "cba_xeh",
            "acre_sys_rack",
            "ace_explosives",
            "ace_parachute",
            "A3_Characters_F_Mark",
            "A3_Characters_F_Jets",
            "A3_Characters_F_Orange",
            "A3_Characters_F_Tank"
        };
        author = "A.Weber";
        authors[] = {"A.Weber"};
    };
};
//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 220.153034 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_IN {
        displayName = "[SFT] Koslovics";
        side = 0;
        flag = "\TCP\UI_F_TCP\Data\Map\Markers\Flags\INS_ca.paa";
        icon = "\TCP\UI_F_TCP\Data\Map\Markers\Flags\INS_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_IN {
            name = "[SFT] Koslovics";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_lite_F;
    class O_Soldier_lite_F_OCimport_01 : O_Soldier_lite_F { scope = 0; class EventHandlers; };
    class O_Soldier_lite_F_OCimport_02 : O_Soldier_lite_F_OCimport_01 { class EventHandlers; };

    class O_officer_F;
    class O_officer_F_OCimport_01 : O_officer_F { scope = 0; class EventHandlers; };
    class O_officer_F_OCimport_02 : O_officer_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_GL_F;
    class O_Soldier_GL_F_OCimport_01 : O_Soldier_GL_F { scope = 0; class EventHandlers; };
    class O_Soldier_GL_F_OCimport_02 : O_Soldier_GL_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_AR_F;
    class O_Soldier_AR_F_OCimport_01 : O_Soldier_AR_F { scope = 0; class EventHandlers; };
    class O_Soldier_AR_F_OCimport_02 : O_Soldier_AR_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_SL_F;
    class O_Soldier_SL_F_OCimport_01 : O_Soldier_SL_F { scope = 0; class EventHandlers; };
    class O_Soldier_SL_F_OCimport_02 : O_Soldier_SL_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_TL_F;
    class O_Soldier_TL_F_OCimport_01 : O_Soldier_TL_F { scope = 0; class EventHandlers; };
    class O_Soldier_TL_F_OCimport_02 : O_Soldier_TL_F_OCimport_01 { class EventHandlers; };

    class O_soldier_M_F;
    class O_soldier_M_F_OCimport_01 : O_soldier_M_F { scope = 0; class EventHandlers; };
    class O_soldier_M_F_OCimport_02 : O_soldier_M_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_LAT_F;
    class O_Soldier_LAT_F_OCimport_01 : O_Soldier_LAT_F { scope = 0; class EventHandlers; };
    class O_Soldier_LAT_F_OCimport_02 : O_Soldier_LAT_F_OCimport_01 { class EventHandlers; };

    class O_medic_F;
    class O_medic_F_OCimport_01 : O_medic_F { scope = 0; class EventHandlers; };
    class O_medic_F_OCimport_02 : O_medic_F_OCimport_01 { class EventHandlers; };

    class O_soldier_repair_F;
    class O_soldier_repair_F_OCimport_01 : O_soldier_repair_F { scope = 0; class EventHandlers; };
    class O_soldier_repair_F_OCimport_02 : O_soldier_repair_F_OCimport_01 { class EventHandlers; };

    class O_soldier_exp_F;
    class O_soldier_exp_F_OCimport_01 : O_soldier_exp_F { scope = 0; class EventHandlers; };
    class O_soldier_exp_F_OCimport_02 : O_soldier_exp_F_OCimport_01 { class EventHandlers; };

    class O_helipilot_F;
    class O_helipilot_F_OCimport_01 : O_helipilot_F { scope = 0; class EventHandlers; };
    class O_helipilot_F_OCimport_02 : O_helipilot_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_A_F;
    class O_Soldier_A_F_OCimport_01 : O_Soldier_A_F { scope = 0; class EventHandlers; };
    class O_Soldier_A_F_OCimport_02 : O_Soldier_A_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_AT_F;
    class O_Soldier_AT_F_OCimport_01 : O_Soldier_AT_F { scope = 0; class EventHandlers; };
    class O_Soldier_AT_F_OCimport_02 : O_Soldier_AT_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_AA_F;
    class O_Soldier_AA_F_OCimport_01 : O_Soldier_AA_F { scope = 0; class EventHandlers; };
    class O_Soldier_AA_F_OCimport_02 : O_Soldier_AA_F_OCimport_01 { class EventHandlers; };

    class O_engineer_F;
    class O_engineer_F_OCimport_01 : O_engineer_F { scope = 0; class EventHandlers; };
    class O_engineer_F_OCimport_02 : O_engineer_F_OCimport_01 { class EventHandlers; };

    class O_crew_F;
    class O_crew_F_OCimport_01 : O_crew_F { scope = 0; class EventHandlers; };
    class O_crew_F_OCimport_02 : O_crew_F_OCimport_01 { class EventHandlers; };

    class O_Pilot_F;
    class O_Pilot_F_OCimport_01 : O_Pilot_F { scope = 0; class EventHandlers; };
    class O_Pilot_F_OCimport_02 : O_Pilot_F_OCimport_01 { class EventHandlers; };

    class O_helicrew_F;
    class O_helicrew_F_OCimport_01 : O_helicrew_F { scope = 0; class EventHandlers; };
    class O_helicrew_F_OCimport_02 : O_helicrew_F_OCimport_01 { class EventHandlers; };

    class O_soldier_UAV_F;
    class O_soldier_UAV_F_OCimport_01 : O_soldier_UAV_F { scope = 0; class EventHandlers; };
    class O_soldier_UAV_F_OCimport_02 : O_soldier_UAV_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_AAR_F;
    class O_Soldier_AAR_F_OCimport_01 : O_Soldier_AAR_F { scope = 0; class EventHandlers; };
    class O_Soldier_AAR_F_OCimport_02 : O_Soldier_AAR_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_AAT_F;
    class O_Soldier_AAT_F_OCimport_01 : O_Soldier_AAT_F { scope = 0; class EventHandlers; };
    class O_Soldier_AAT_F_OCimport_02 : O_Soldier_AAT_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_AAA_F;
    class O_Soldier_AAA_F_OCimport_01 : O_Soldier_AAA_F { scope = 0; class EventHandlers; };
    class O_Soldier_AAA_F_OCimport_02 : O_Soldier_AAA_F_OCimport_01 { class EventHandlers; };

    class O_support_AMG_F;
    class O_support_AMG_F_OCimport_01 : O_support_AMG_F { scope = 0; class EventHandlers; };
    class O_support_AMG_F_OCimport_02 : O_support_AMG_F_OCimport_01 { class EventHandlers; };

    class O_Sharpshooter_F;
    class O_Sharpshooter_F_OCimport_01 : O_Sharpshooter_F { scope = 0; class EventHandlers; };
    class O_Sharpshooter_F_OCimport_02 : O_Sharpshooter_F_OCimport_01 { class EventHandlers; };

    class O_HeavyGunner_F;
    class O_HeavyGunner_F_OCimport_01 : O_HeavyGunner_F { scope = 0; class EventHandlers; };
    class O_HeavyGunner_F_OCimport_02 : O_HeavyGunner_F_OCimport_01 { class EventHandlers; };

    class O_Fighter_Pilot_F;
    class O_Fighter_Pilot_F_OCimport_01 : O_Fighter_Pilot_F { scope = 0; class EventHandlers; };
    class O_Fighter_Pilot_F_OCimport_02 : O_Fighter_Pilot_F_OCimport_01 { class EventHandlers; };

    class O_soldier_mine_F;
    class O_soldier_mine_F_OCimport_01 : O_soldier_mine_F { scope = 0; class EventHandlers; };
    class O_soldier_mine_F_OCimport_02 : O_soldier_mine_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_HAT_F;
    class O_Soldier_HAT_F_OCimport_01 : O_Soldier_HAT_F { scope = 0; class EventHandlers; };
    class O_Soldier_HAT_F_OCimport_02 : O_Soldier_HAT_F_OCimport_01 { class EventHandlers; };

    class O_Soldier_AHAT_F;
    class O_Soldier_AHAT_F_OCimport_01 : O_Soldier_AHAT_F { scope = 0; class EventHandlers; };
    class O_Soldier_AHAT_F_OCimport_02 : O_Soldier_AHAT_F_OCimport_01 { class EventHandlers; };


    class O_IN_Rifleman_01 : O_Soldier_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_ALFA_Green","SA_HM03_Lynx_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_ALFA_Green","SA_HM03_Lynx_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_ALFA_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32}}},"SA_HM03_Lynx_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Rifleman_light_01 : O_Soldier_lite_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (light)";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_IA70_ALFA_Green","TCP_H_Cap_Woodland_Reversed","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_IA70_ALFA_Green","TCP_H_Cap_Woodland_Reversed","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_M6J"};
        respawnWeapons[] = {"SFT_M6J"};

        magazines[] = {"SFT_24Rnd_127x30_46_Mag","SFT_24Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_24Rnd_127x30_46_Mag","SFT_24Rnd_127x30_46_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"SFT_M6J","TCP_muzzle_flash_127_01","","SFT_optic_ERO",{"SFT_24Rnd_127x30_46_Mag",24},{},"TCP_bipod_handGuard_M6G"},{},{},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_IA70_ALFA_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_24Rnd_127x30_46_Mag_Tracer",4,24}}},{},"TCP_H_Cap_Woodland_Reversed","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Officer_01 : O_officer_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_officer"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_IA70_ALFA_Green","Frieden_Beret","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_IA70_ALFA_Green","Frieden_Beret","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_M6J","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_M6J","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_24Rnd_127x30_46_Mag","TCP_8Rnd_127x30_46_Mag","SFT_24Rnd_127x30_46_Mag","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_24Rnd_127x30_46_Mag","TCP_8Rnd_127x30_46_Mag","SFT_24Rnd_127x30_46_Mag","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_M6J","TCP_muzzle_flash_127_01","","SFT_optic_ERO_Blue",{"SFT_24Rnd_127x30_46_Mag",24},{},"TCP_bipod_handGuard_M6G"},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_IA70_ALFA_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"TCP_8Rnd_127x30_46_Mag",2,8},{"SFT_24Rnd_127x30_46_Mag_Tracer",4,24}}},{"OPTRE_UNSC_Rucksack",{}},"Frieden_Beret","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Grenadier_01 : O_Soldier_GL_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA90_Alfa_Green","SA_HM03_Lynx_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA90_Alfa_Green","SA_HM03_Lynx_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37GL","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37GL","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"M319_HE_Grenade_Shell","TCP_8Rnd_127x30_46_Mag","M319_HE_Grenade_Shell","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"M319_HE_Grenade_Shell","TCP_8Rnd_127x30_46_Mag","M319_HE_Grenade_Shell","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37GL","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{},{"M319_HE_Grenade_Shell",1},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1},{"SFT_32Rnd_762x51_Mag_Tracer",1,32}}},{"SA_HA90_Alfa_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"M319_HE_Grenade_Shell",5,1},{"M319_HEDP_Grenade_Shell",2,1},{"OPTRE_signalSmokeB",2,1},{"OPTRE_signalSmokeG",2,1},{"OPTRE_signalSmokeR",2,1},{"OPTRE_3Rnd_Smoke_Grenade_shell",2,3},{"ACE_40mm_Flare_white",10,1},{"ACE_40mm_Flare_green",2,1},{"ACE_40mm_Flare_red",2,1}}},"SA_HM03_Lynx_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Autorifleman_01 : O_Soldier_AR_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA90_Charlie_Green","SA_HM04S_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA90_Charlie_Green","SA_HM04S_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_M739","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_M739","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_762x51_M739_Box","TCP_8Rnd_127x30_46_Mag","SFT_762x51_M739_Box","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_762x51_M739_Box","TCP_8Rnd_127x30_46_Mag","SFT_762x51_M739_Box","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"SFT_M739","TCP_muzzle_brake_762_01","","OPTRE_M739_SAW_Smartlink",{"SFT_762x51_M739_Box",192},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA90_Charlie_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"SFT_762x51_M739_Box",5,192}}},"SA_HM04S_Ocelot_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Squad_Leader_01 : O_Soldier_SL_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_CHARLIE_Green","SA_HM05S_Fox_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_CHARLIE_Green","SA_HM05S_Fox_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "TCF_RUCKSACK_UNSC_WDL_RAD_F";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_CHARLIE_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"TCP_8Rnd_127x30_46_Mag",2,8},{"SFT_32Rnd_762x51_Mag_Tracer",4,32}}},{"TCF_RUCKSACK_UNSC_WDL_RAD_F",{{"ACRE_PRC152",1},{"ACRE_PRC117F",1},{"SFT_32Rnd_762x51_Mag_Tracer",1,32}}},"SA_HM05S_Fox_S_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Team_Leader_01 : O_Soldier_TL_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA90_Charlie_Green","SA_HM05_Fox_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA90_Charlie_Green","SA_HM05_Fox_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37GL","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37GL","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"M319_HE_Grenade_Shell","TCP_8Rnd_127x30_46_Mag","M319_HE_Grenade_Shell","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"M319_HE_Grenade_Shell","TCP_8Rnd_127x30_46_Mag","M319_HE_Grenade_Shell","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37GL","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{},{"M319_HE_Grenade_Shell",1},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1},{"SFT_32Rnd_762x51_Mag_Tracer",1,32}}},{"SA_HA90_Charlie_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"ACRE_PRC152",1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"M319_HE_Grenade_Shell",2,1},{"OPTRE_signalSmokeB",2,1},{"OPTRE_signalSmokeG",2,1},{"OPTRE_signalSmokeR",2,1},{"OPTRE_3Rnd_Smoke_Grenade_shell",2,3}}},"SA_HM05_Fox_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Marksman_01 : O_soldier_M_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_ECHO_Green","SA_HM04E_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_ECHO_Green","SA_HM04E_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_M392","TCP_hgun_Pistol_M6G2_F","CTGCY_H155_LD"};
        respawnWeapons[] = {"SFT_M392","TCP_hgun_Pistol_M6G2_F","CTGCY_H155_LD"};

        magazines[] = {"SFT_15Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","Laserbatteries","SFT_15Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","Laserbatteries"};
        respawnMagazines[] = {"SFT_15Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","Laserbatteries","SFT_15Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"SFT_M392","TCP_muzzle_brake_762_01","","SFT_optic_EVOSD_SL",{"SFT_15Rnd_762x51_Mag_Tracer",15},{},"TCP_bipod_01"},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_ECHO_Green",{{"ACE_RangeCard",1},{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"TCP_8Rnd_127x30_46_Mag",2,8},{"SFT_15Rnd_762x51_Mag_Tracer",8,15}}},{},"SA_HM04E_Ocelot_Green","TCP_G_VisrGlasses",{"CTGCY_H155_LD","","","",{"Laserbatteries",1},{},""},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Rifleman_Disposable_01 : O_Soldier_LAT_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (Disposable)";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_BRAVO_Green","SA_HM03S_Lynx_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_BRAVO_Green","SA_HM03S_Lynx_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","DMNS_M96_LAW","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","DMNS_M96_LAW","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{"DMNS_M96_LAW","","","",{},{},""},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_BRAVO_Green",{{"DMNS_M96_HEAT",1,1},{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",2,32}}},{"OPTRE_UNSC_Rucksack",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32}}},"SA_HM03S_Lynx_S_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Medic_01 : O_medic_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_ECHO_Green","SA_HM05E_Tiger_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_ECHO_Green","SA_HM05E_Tiger_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Medic";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_ECHO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack_Medic",{{"kat_MFAK",2},{"ACE_surgicalKit",1},{"ACE_personalAidKit",1},{"kat_accuvac",1},{"kat_X_AED",1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32}}},"SA_HM05E_Tiger_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Repair_Specialist_01 : O_soldier_repair_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Repair Specialist";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_ALFA_Green","SA_HM05S_Fox_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_ALFA_Green","SA_HM05S_Fox_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_ALFA_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"advrepair_ToolkitLight",1},{"advrepair_SpareParts",3},{"SFT_32Rnd_762x51_Mag_Tracer",4,32}}},"SA_HM05S_Fox_S_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Explosive_Specialist_01 : O_soldier_exp_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Explosive Specialist";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_IA70_BRAVO_Green","SA_HM05C_Fox_C_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_IA70_BRAVO_Green","SA_HM05C_Fox_C_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_IA70_BRAVO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"ACE_Clacker",1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"C7_Remote_Mag",4,1},{"C12_Remote_Mag",2,1}}},"SA_HM05C_Fox_C_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Helicopter_Pilot_01 : O_helipilot_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Helicopter Pilot";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_I_pilotCoveralls";

        linkedItems[] = {"19th_invisible_Vest","H_PilotHelmetHeli_O","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"19th_invisible_Vest","H_PilotHelmetHeli_O","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};

        weapons[] = {"SFT_M6J"};
        respawnWeapons[] = {"SFT_M6J"};

        magazines[] = {"SFT_24Rnd_127x30_46_Mag","SFT_24Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_24Rnd_127x30_46_Mag","SFT_24Rnd_127x30_46_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"SFT_M6J","TCP_muzzle_flash_127_01","","SFT_optic_ERO_Blue",{"SFT_24Rnd_127x30_46_Mag",24},{},"TCP_bipod_handGuard_M6G"},{},{},{"U_I_pilotCoveralls",{{"FirstAidKit",1},{"SmokeShellRed",1,1},{"SmokeShellOrange",1,1},{"SmokeShellYellow",1,1},{"Chemlight_red",2,1}}},{"19th_invisible_Vest",{{"SFT_24Rnd_127x30_46_Mag_Tracer",2,24}}},{},"H_PilotHelmetHeli_O","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Ammo_Bearer_01 : O_Soldier_A_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ammo Bearer";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_IA70_BRAVO_Green","SA_HM04_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_IA70_BRAVO_Green","SA_HM04_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_IA70_BRAVO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"SFT_32Rnd_762x51_Mag_Tracer",10,32},{"SFT_M319_HE_Grenade_Shell",3,3},{"SFT_100Rnd_762x51_mag",2,100},{"SFT_15Rnd_762x51_Mag_Tracer",3,15},{"SFT_24Rnd_127x30_46_Mag_Tracer",2,24},{"SFT_50Rnd_127x99_M250_Box",1,50}}},"SA_HM04_Ocelot_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Missile_Specialist_AT_01 : O_Soldier_AT_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Missile Specialist (AT)";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_BRAVO_Green","SA_HM03S_Lynx_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_BRAVO_Green","SA_HM03S_Lynx_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCF_M57_Pilum_b","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCF_M57_Pilum_b","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCF_2Rnd_50x137_HEAT","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCF_2Rnd_50x137_HEAT","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{"TCF_M57_Pilum_b","","","TCF_M57_QAS2",{"TCF_2Rnd_50x137_HEAT",2},{},""},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_BRAVO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCF_2Rnd_50x137_HEAT",2,2}}},"SA_HM03S_Lynx_S_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Missile_Specialist_AA_01 : O_Soldier_AA_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Missile Specialist (AA)";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_BRAVO_Green","SA_HM03S_Lynx_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_BRAVO_Green","SA_HM03S_Lynx_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","SFT_M41","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","SFT_M41","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","SFT_2Rnd_102mm_Mag_HEAT_G_AA","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","SFT_2Rnd_102mm_Mag_HEAT_G_AA","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{"SFT_M41","","","",{"SFT_2Rnd_102mm_Mag_HEAT_G_AA",2},{},""},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_BRAVO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"SFT_2Rnd_102mm_Mag_HEAT_G_AA",2,2}}},"SA_HM03S_Lynx_S_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Engineer_01 : O_engineer_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_ALFA_Green","SA_HM04_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_ALFA_Green","SA_HM04_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1},{"cigs_cigars_cigarbox_5",1,5},{"cigs_matches",1,10}}},{"SA_HA80_ALFA_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"ToolKit",1},{"advrepair_SpareParts",5},{"SFT_32Rnd_762x51_Mag_Tracer",4,32}}},"SA_HM04_Ocelot_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Crewman_01 : O_crew_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_IA70_ALFA_Green","SA_HM04S_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_IA70_ALFA_Green","SA_HM04S_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_M7","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_M7","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"60Rnd_5x23_m7_fmj_tracer","TCP_8Rnd_127x30_46_Mag","60Rnd_5x23_m7_fmj_tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"60Rnd_5x23_m7_fmj_tracer","TCP_8Rnd_127x30_46_Mag","60Rnd_5x23_m7_fmj_tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_M7","","","SFT_optic_M7",{"60Rnd_5x23_m7_fmj_tracer",60},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_IA70_ALFA_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{}},"SA_HM04S_Ocelot_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Pilot_01 : O_Pilot_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_I_pilotCoveralls";

        linkedItems[] = {"H_PilotHelmetFighter_O","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_PilotHelmetFighter_O","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"SFT_M6J"};
        respawnWeapons[] = {"SFT_M6J"};

        magazines[] = {"SFT_12Rnd_127x30_46_Mag_Tracer","SFT_12Rnd_127x30_46_Mag_Tracer"};
        respawnMagazines[] = {"SFT_12Rnd_127x30_46_Mag_Tracer","SFT_12Rnd_127x30_46_Mag_Tracer"};

        backpack = "ACE_NonSteerableParachute";

        ALiVE_orbatCreator_loadout[] = {{"SFT_M6J","TCP_muzzle_flash_127_01","","SFT_optic_ERO_Blue",{"SFT_12Rnd_127x30_46_Mag_Tracer",12},{},"TCP_bipod_handGuard_M6G"},{},{},{"U_I_pilotCoveralls",{{"FirstAidKit",1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",1,1}}},{},{"ACE_NonSteerableParachute",{}},"H_PilotHelmetFighter_O","TCP_G_CBUU_Balaclava",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Helicopter_Crew_01 : O_helicrew_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Helicopter Crew";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_I_pilotCoveralls";

        linkedItems[] = {"V_TacVest_oli","H_CrewHelmetHeli_O","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"V_TacVest_oli","H_CrewHelmetHeli_O","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};

        weapons[] = {"SFT_M6J"};
        respawnWeapons[] = {"SFT_M6J"};

        magazines[] = {"SFT_24Rnd_127x30_46_Mag","SFT_24Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_24Rnd_127x30_46_Mag","SFT_24Rnd_127x30_46_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"SFT_M6J","TCP_muzzle_flash_127_01","","SFT_optic_ERO_Blue",{"SFT_24Rnd_127x30_46_Mag",24},{},"TCP_bipod_handGuard_M6G"},{},{},{"U_I_pilotCoveralls",{{"FirstAidKit",1},{"SmokeShellRed",1,1},{"SmokeShellOrange",1,1},{"SmokeShellYellow",1,1},{"Chemlight_red",2,1}}},{"V_TacVest_oli",{}},{},"H_CrewHelmetHeli_O","TCP_G_VisrGlasses",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_UAV_Operator_01 : O_soldier_UAV_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAV Operator";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_IA70_ALFA_Green","SA_HM05SF_Coyote_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_IA70_ALFA_Green","SA_HM05SF_Coyote_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "DMNS_UAV_01_backpack_F";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1},{"ACE_UAVBattery",1}}},{"SA_IA70_ALFA_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"DMNS_UAV_01_backpack_F",{}},"SA_HM05SF_Coyote_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Assist_AutoRifleman_01 : O_Soldier_AAR_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assist. AutoRifleman";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA90_Alfa_Green","SA_HM05_Fox_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA90_Alfa_Green","SA_HM05_Fox_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA90_Alfa_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"SFT_762x51_M739_Box",3,192}}},"SA_HM05_Fox_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Assist_Missile_Specialsit_AT_01 : O_Soldier_AAT_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assist. Missile Specialsit (AT)";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_ECHO_Green","SA_HM04_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_ECHO_Green","SA_HM04_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_ECHO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"SFT_2Rnd_102mm_Mag_HEAT",1,2}}},"SA_HM04_Ocelot_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Assist_Missile_Specialist_AA_01 : O_Soldier_AAA_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assist. Missile Specialist (AA)";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_ECHO_Green","SA_HM04_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_ECHO_Green","SA_HM04_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_ECHO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"SFT_2Rnd_102mm_Mag_HEAT_G_AA",1,2}}},"SA_HM04_Ocelot_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Assist_Heavy_AutoRifleman_01 : O_support_AMG_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assist. Heavy AutoRifleman";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_BRAVO_Green","SA_HM03_Lynx_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_BRAVO_Green","SA_HM03_Lynx_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_BRAVO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"SFT_50Rnd_127x99_M250_Box",3,50}}},"SA_HM03_Lynx_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Sharpshooter_01 : O_Sharpshooter_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sharpshooter";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_CHARLIE_Green","SA_HM06_Wolf_Green","ItemMap","ItemGPS","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_CHARLIE_Green","SA_HM06_Wolf_Green","ItemMap","ItemGPS","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_SRS99AM","TCP_hgun_Pistol_M6G2_F","CTGCY_H155_LD"};
        respawnWeapons[] = {"SFT_SRS99AM","TCP_hgun_Pistol_M6G2_F","CTGCY_H155_LD"};

        magazines[] = {"4Rnd_145x114_srs99_apfsds_tracer","TCP_8Rnd_127x30_46_Mag","Laserbatteries","4Rnd_145x114_srs99_apfsds_tracer","TCP_8Rnd_127x30_46_Mag","Laserbatteries"};
        respawnMagazines[] = {"4Rnd_145x114_srs99_apfsds_tracer","TCP_8Rnd_127x30_46_Mag","Laserbatteries","4Rnd_145x114_srs99_apfsds_tracer","TCP_8Rnd_127x30_46_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"SFT_SRS99AM","","","SFT_optic_SRS99AM",{"4Rnd_145x114_srs99_apfsds_tracer",4},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_CHARLIE_Green",{{"ACE_RangeCard",1},{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"TCP_8Rnd_127x30_46_Mag",2,8},{"4Rnd_145x114_srs99_apfsds_tracer",3,4}}},{},"SA_HM06_Wolf_Green","",{"CTGCY_H155_LD","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Heavy_AutoRifleman_01 : O_HeavyGunner_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy AutoRifleman";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_DELTA_Green","SA_HM03S_Lynx_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_DELTA_Green","SA_HM03S_Lynx_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_M250","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_M250","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_50Rnd_127x99_M250_Box","TCP_8Rnd_127x30_46_Mag","SFT_50Rnd_127x99_M250_Box","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_50Rnd_127x99_M250_Box","TCP_8Rnd_127x30_46_Mag","SFT_50Rnd_127x99_M250_Box","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"SFT_M250","TCP_muzzle_brake_762_01","","",{"SFT_50Rnd_127x99_M250_Box",50},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_DELTA_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"TCP_8Rnd_127x30_46_Mag",2,8},{"SFT_50Rnd_127x99_M250_Box",1,50}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"SFT_50Rnd_127x99_M250_Box",8,50}}},"SA_HM03S_Lynx_S_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Fighter_Pilot_01 : O_Fighter_Pilot_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Fighter Pilot";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "U_I_pilotCoveralls";

        linkedItems[] = {"H_PilotHelmetFighter_O","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_PilotHelmetFighter_O","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"TCP_8Rnd_127x30_52_Mag","TCP_8Rnd_127x30_52_Mag"};
        respawnMagazines[] = {"TCP_8Rnd_127x30_52_Mag","TCP_8Rnd_127x30_52_Mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_52_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"U_I_pilotCoveralls",{{"FirstAidKit",1},{"SmokeShellOrange",1,1},{"Chemlight_green",2,1}}},{},{},"H_PilotHelmetFighter_O","TCP_G_VisrGlasses",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Mine_Specialist_01 : O_soldier_mine_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mine Specialist";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_IA70_BRAVO_Green","SA_HM05C_Fox_C_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_IA70_BRAVO_Green","SA_HM05C_Fox_C_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_IA70_BRAVO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"ACE_Clacker",1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"UNSCMine_Range_Mag",2,1},{"APERSBoundingMine_Range_Mag",5,1}}},"SA_HM05C_Fox_C_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Rifleman_Heavy_AT_01 : O_Soldier_HAT_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (Heavy AT)";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_BRAVO_Green","SA_HM03S_Lynx_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_BRAVO_Green","SA_HM03S_Lynx_S_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCF_M57_Pilum_b","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCF_M57_Pilum_b","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCF_2Rnd_50x137_PEN","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCF_2Rnd_50x137_PEN","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{"TCF_M57_Pilum_b","","","TCF_M57_QAS2",{"TCF_2Rnd_50x137_PEN",2},{},""},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_BRAVO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCF_2Rnd_50x137_THERMO",1,2},{"TCF_2Rnd_50x137_PEN",1,2}}},"SA_HM03S_Lynx_S_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_IN_Assist_Rifleman_Heavy_AT_01 : O_Soldier_AHAT_F_OCimport_02 {
        author = "A.Weber";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assist. Rifleman (Heavy AT)";
        side = 0;
        faction = "O_IN";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "SA_CU10G_UNI";

        linkedItems[] = {"SA_HA80_ECHO_Green","SA_HM04_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};
        respawnlinkedItems[] = {"SA_HA80_ECHO_Green","SA_HM04_Ocelot_Green","ItemMap","TCP_RF55","ItemCompass","TCP_Watch"};

        weapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};
        respawnWeapons[] = {"SFT_MA37","TCP_hgun_Pistol_M6G2_F"};

        magazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};
        respawnMagazines[] = {"SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag","SFT_32Rnd_762x51_Mag_Tracer","TCP_8Rnd_127x30_46_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"SFT_MA37","TCP_muzzle_brake_762_01","TCP_acc_pointer_lam_MA37","SFT_optic_EVOSJ_SL",{"SFT_32Rnd_762x51_Mag_Tracer",32},{},""},{},{"TCP_hgun_Pistol_M6G2_F","","","TCP_optic_KFA_M6G2",{"TCP_8Rnd_127x30_46_Mag",8},{},"TCP_bipod_handGuard_M6G2"},{"SA_CU10G_UNI",{{"ACRE_PRC343",1},{"RS_Equip_Retention",1},{"ItemMicroDAGR",1},{"ACE_EarPlugs",1},{"kat_IFAK",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1}}},{"SA_HA80_ECHO_Green",{{"TCP_M21_Smoke",4,1},{"TCP_M9R_Frag",2,1},{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCP_8Rnd_127x30_46_Mag",2,8}}},{"OPTRE_UNSC_Rucksack",{{"SFT_32Rnd_762x51_Mag_Tracer",4,32},{"TCF_2Rnd_50x137_THERMO",1,2}}},"SA_HM04_Ocelot_Green","",{},{"ItemMap","","TCP_RF55","ItemCompass","TCP_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};