name = "StrikeForce Talon Armory"
prefix = "SFT"
author = "Weber"

[files]
include = [
    "mod.cpp",
    "logo.paa",
    "README.md",
    "LICENSE",
    "*.pbo" 
]

exclude = [
    "*.png", # explicitly excluding image source files from build, but not repository
]

[validate]
skipMessages = [
  "Math could be unquoted"
]

[version]
major = 1
minor = 0
patch = 0
build = 0
git_hash = 0